version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --without dev --with docs
    - make build-docs
    - cp -r docs/_build _readthedocs