name: formatting-linting

on:
  pull_request:
    branches:
    - main

jobs:

  check-formatting-linting:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Install dependencies
      run: poetry install

    - name: Check formatting
      run: make format CHECK=1

    - name: Check linting
      run: make lint CHECK=1
