name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      run: make test

    - name: Extract git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1

    - name: Coveralls parallel
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: py-${{ matrix.python-version }}
        git-branch: ${{ env.GIT_BRANCH_NAME }}
        path-to-lcov: coverage.lcov
        parallel: true

  finalize-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1

    - name: Coveralls finish
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-branch: ${{ env.GIT_BRANCH_NAME }}
        parallel-finished: true